<Project>
    <PropertyGroup>
        <ReferencesRoot Condition="'$(ReferencesRoot)' == ''">/home/vapok/Modding/References</ReferencesRoot>
        <ValheimGamePath Condition="'$(ValheimGamePath)' == '' AND '$(OS)' != 'Windows_NT'">$(ReferencesRoot)/Valheim/1.0.16</ValheimGamePath>
        <ValheimGamePath Condition="'$(ValheimGamePath)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Valheim</ValheimGamePath>
        <BepInExPath Condition="'$(BepInExPath)' == '' AND '$(OS)' != 'Windows_NT'">$(ReferencesRoot)/BepInEx/5.4.2350/BepInEx</BepInExPath>
        <BepInExPath Condition="'$(BepInExPath)' == ''">$(ValheimGamePath)\BepInEx</BepInExPath>
        <CorlibPath Condition="'$(CorlibPath)' == '' AND '$(OS)' != 'Windows_NT'">$(ValheimGamePath)/Managed</CorlibPath>
        <CorlibPath Condition="'$(CorlibPath)' == ''">$(ValheimGamePath)\valheim_Data\Managed</CorlibPath>
        <UserProfile Condition="'$(UserProfile)' == '' AND '$(OS)' != 'Windows_NT'">$(HOME)</UserProfile>
        <RuntimeIdentifiers Condition="'$(RuntimeIdentifiers)' == ''">win</RuntimeIdentifiers>
        <DeployToGame Condition="'$(DeployToGame)' == ''">false</DeployToGame>
        <CopyOutputDLLPath Condition="'$(CopyOutputDLLPath)' == ''">$(ValheimGamePath)\BepInEx\plugins</CopyOutputDLLPath>
        <AfterTargets>ILRepacker</AfterTargets>
    </PropertyGroup>
</Project>
